### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by jpfree** [drobban/joy_udprc#1]
hello,thanks for your share ,but i want to know to use it?what king of hardware?

**Comment by drobban** [comment]
To begin with, the code is written for OpenBSD and maybe NetBSD as well.

To make it work, you need a "modified" version of ardupilot with UDP communication activated.

Long time since I worked with the code and I would recommend using https://github.com/jberaud/joystick_remote
if you want something that works almost out of the box for Linux...

Minor tweaks is needed if you use another kind of joystick then the one intended in the code.

I have used it together with Emlid Navio and Nvidia Shield USB joystick
